src/VTBlog.WebApp/Components/PagerViewComponent.cs
using Microsoft.AspNetCore.Mvc;
using VTBlog.Core.Models;

namespace VTBlog.WebApp.Components
{
    public class PagerViewComponent:ViewComponent
    {
        public Task<IViewComponentResult> InvokeAsync(PagedResultBase result)
        {
            return Task.FromResult((IViewComponentResult) View("Default", result));
        }
    }
}

src/VTBlog.WebApp/Controllers/SeriesController.cs
using Microsoft.AspNetCore.Mvc;
using VTBlog.Core.SeedWorks;
using VTBlog.WebApp.Models;

namespace VTBlog.WebApp.Controllers
{
    public class SeriesController(IUnitOfWork unitOfWork) : Controller
    {
        private readonly IUnitOfWork _unitOfWork = unitOfWork;

        [Route("/series")]
        public async Task<IActionResult> Index([FromQuery] int page=1)
        {
            var series = await _unitOfWork.Series.GetAllPaging(string.Empty, page);
            return View(series);
        }

        [Route("series/{slug}")]
        public async Task<IActionResult> Details([FromRoute] string slug)
        {
            var posts = await _unitOfWork.Series.GetAllPostsInSeries(slug);
            var series = await _unitOfWork.Series.GetBySlug(slug);
            return View(new SeriesDetailViewModel()
            {
                Posts = posts,
                Series = series
            });
        }
    }
}

src/VTBlog.WebApp/Views/Series/Details.cshtml
@model SeriesDetailViewModel
@{
    ViewData["Title"] = Model.Series.Name + (Model.Posts.CurrentPage > 1 ? $" - Trang {Model.Posts.CurrentPage}" : "");
    ViewData["Description"] = Model.Series.SeoDescription + (Model.Posts.CurrentPage > 1 ? $" - Trang {Model.Posts.CurrentPage}" : "");
}
<!-- Page Header-->
<header class="masthead" style="background-image: url('/assets/img/home-bg.jpg')">
    <div class="container position-relative px-4 px-lg-5">
        <div class="row gx-4 gx-lg-5 justify-content-center">
            <div class="col-md-10 col-lg-8 col-xl-7">
                <div class="site-heading">
                    <h1>@Model.Series.Name</h1>
                </div>
            </div>
        </div>
    </div>
</header>
<!-- Main Content-->
<div class="container px-4 px-lg-5">
    <div class="row gx-4 gx-lg-5 justify-content-center">
        <div class="col-md-10 col-lg-8 col-xl-7">
            @foreach (var item in Model.Posts.Results)
            {
                <!-- Post preview-->
                <div class="post-preview">
                    <a href="@string.Format(UrlConsts.PostDetails,item.Slug)" title="@item.Name">
                        <h2 class="post-title">@item.Name</h2>
                        <h3 class="post-subtitle">@item.Description</h3>
                    </a>
                    <p class="post-meta">
                        Posted by
                        <a href="@string.Format(UrlConsts.Author,item.AuthorUserName)">@item.AuthorName</a>
                        on @item.DateCreated.ToLongTimeString()
                    </p>
                </div>
                <!-- Divider-->
                <hr class="my-4" />
            }
            <!-- Pager-->
            @(await Component.InvokeAsync("Pager", Model.Posts))
        </div>
    </div>
</div>

src/VTBlog.WebApp/Views/Series/Index.cshtml
@using VTBlog.Core.Models
@using VTBlog.Core.Models.Content
@model PagedResult<SeriesInListDto>
@{
    ViewData["Title"] = "Series posts" + (Model.CurrentPage > 1 ? $" - Trang {Model.CurrentPage}" : "");
    ViewData["Description"] = "Series posts" + (Model.CurrentPage > 1 ? $" - Trang {Model.CurrentPage}" : "");
}

<!-- Page Header-->
<header class="masthead" style="background-image: url('/assets/img/home-bg.jpg')">
    <div class="container position-relative px-4 px-lg-5">
        <div class="row gx-4 gx-lg-5 justify-content-center">
            <div class="col-md-10 col-lg-8 col-xl-7">
                <div class="site-heading">
                    <h1>Series</h1>
                </div>
            </div>
        </div>
    </div>
</header>
<!-- Main Content-->
<div class="container px-4 px-lg-5">
    <div class="row gx-4 gx-lg-5 justify-content-center">
        <div class="col-md-10 col-lg-8 col-xl-7">
            @foreach (var item in Model.Results)
            {
                <!-- Post preview-->
                <div class="post-preview">
                    <a href="@string.Format(UrlConsts.SeriesDetail,item.Slug)" title="@item.Name">
                        <h2 class="post-title">@item.Name</h2>
                        <h3 class="post-subtitle">@item.Description</h3>
                    </a>
                </div>
                <!-- Divider-->
                <hr class="my-4" />
            }
            <!-- Pager-->
            @(await Component.InvokeAsync("Pager", Model))
        </div>
    </div>
</div>